create table tb_role (id_role int8 generated by default as identity, role_name varchar(255), primary key (id_role));
create table tb_user (id_user int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id_user));
create table tb_user_role (id_user int8 not null, id_role int8 not null, primary key (id_user, id_role));
alter table if exists tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table if exists tb_user_role add constraint FKqyah3h8pvegx25e1ws2uqqh3w foreign key (id_role) references tb_role;
alter table if exists tb_user_role add constraint FK2ofk22xlwowni569oxg08rrgn foreign key (id_user) references tb_user;
