create table tb_worker (id_worker int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id_worker));
create table tb_worker (id_worker int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id_worker));
